# Generated by Django 3.1 on 2021-04-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_ban_gnk_ict_mat_sci'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ban',
        ),
    ]
