# Generated by Django 3.1 on 2021-04-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_ban'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bangla',
        ),
        migrations.DeleteModel(
            name='GK',
        ),
        migrations.DeleteModel(
            name='GNK',
        ),
        migrations.DeleteModel(
            name='Mat',
        ),
        migrations.DeleteModel(
            name='Math',
        ),
        migrations.DeleteModel(
            name='Sci',
        ),
        migrations.DeleteModel(
            name='Science',
        ),
    ]
