# Generated by Django 3.1 on 2021-04-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_books_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
